### ISSUE TITLE
Default for delete prompt should be [N]o

### ISSUE THREAD

**Issue by grandchild** [hartwork/git-delete-merged-branches#1]
> `git-delete-merged-branches` takes safety seriously.

If so, the default selection on the "Delete?" prompt should be `N`, not `Y`.
```
$git-delete-merged-branches
You are about to delete 1 local branche(s):
 - xxxxxx
Delete? [Y/n]
```

Should instead be:
```
Delete? [y/N]
```

**Comment by hartwork** [comment]
It was a conscious decision (and inspired by use of apt and portage) but maybe I missed something. Why would you say it's important to have the default be no?

**Comment by grandchild** [comment]
Not too familiar with apt, but I imagine most of the commands are non-destructive in the sense that even when you uninstall something you can quickly install it again.

After claiming to take safety seriously I feel like a destructive action should be made explicit, like (c)fdisk etc.

But it's a matter of preference and I don't feel too strongly about it.

**Comment by hartwork** [comment]
I thought about it more — I think you're right, let me flip it around.
