### ISSUE TITLE
Section name in .git/config too cryptic

### ISSUE THREAD

**Issue by grandchild** [hartwork/git-delete-merged-branches#13]
I suppose having just `[dmb]` looks nice and clean, and I guess that was the rationale behind choosing that as the section name for the gitconfig.

However, when coming from the other side, namely looking at one's gitconfig and trying to figure out what all these sections and keys are for, it's basically indecipherable, and thus very hard to discover what `[dmb] configured = true` is doing and whether I want it.

I'd suggest changing it to `[delete-merged-branches] configured = true` because that would make me search for "git delete-merged-branches" and probably wind up here. What do you think?

**Comment by grandchild** [comment]
It's debatable whether this early in the project history and with (supposedly) this few users, that this would require a "migration" -- deleting the previous `[dmb]` section for existing users and replacing it with the new one.

**Comment by hartwork** [comment]
Alright, I think you have a point here :+1: I'll do a mayor version bump to reflect that change in API.

**Comment by hartwork** [comment]
I won't change `.dmb-enabled = true` for now. Let me me know if that's as important to change.

**Comment by hartwork** [comment]
> I'd suggest changing it to `[delete-merged-branches] configured = true` because that would make me search for "git delete-merged-branches" and probably wind up here. What do you think?

Released 4.0.0 with a change like that in 04e89680cff703cd992172f2716fe76eb61cf710 just now. Do you consider this fixed?

**Comment by grandchild** [comment]
I do.
