### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Atrate** [hartwork/git-delete-merged-branches#15]
Hey there!

It would be beneficial if you specified under which license you have released this tool and source code (e.g. GPLv3) or whether you consider it All Rights Reserved.

**Comment by hartwork** [comment]
Hi!

The code is license under "GPL v3 or later": Every python file header in here has a comment (unless I missed some?) and `setup.py` puts it into the package metadata as well. Which place do you consider missing a statement about the license?

Best, Sebastian

**Comment by Atrate** [comment]
Doesn't the GPL require for the complete copy of the license to be distributed with the code? E.g. as a LICENSE file.

http://www.gnu.org/licenses/gpl-howto.html

**Comment by hartwork** [comment]
I have added a license file now. Closing as fixed, please re-open as needed.
