### ISSUE TITLE
Error: One or more existing target branch is required.

### ISSUE THREAD

**Issue by FrederikLauber** [hartwork/git-delete-merged-branches#159]
Hi,

I already saw that similar issues exist but they are either closed or resolved so I guess I stumbled onto something new.

I ahve been using git-delete-merged-branches for some time now and it seems to have randomly stopped working. Maybe it is due to a branch I created or some mistreatment of my git repo.

As this happened in the repository at work, I may neet to anonymous data from the repo but I would really like to track this down.

**Comment by hartwork** [comment]
Hi @FrederikLauber,

from what you have shared so far, it would be difficult for me to really understand the issue beyond just guessing. I can offer to jump on a voice in English or German call with you. If interested, please drop a mail about your availability to the e-mail address mentioned my GitHub Profile page.

If you need a quick workaround, probably running `git-delete-merged-branches --configure` will work, but maybe leave one of the the affected repositories (or make a full backup including the `.git` folder before) so that we still have something real to debug later.

Best, Sebastian

**Comment by FrederikLauber** [comment]
Dropped you en email with my contact data :)

**Comment by FrederikLauber** [comment]
Hi, 

problem was solved during the call.

I had deleted my master branch and pulled it from the server again. 
This removed the flag "dmb-required = true" from .git/config, section branch "master". Thus,  git-delete-merged-branches  could not detect which branches are to be checked for merges.
A git-delete-merged-branches --configure and setting master as the to be merged branch solved the issue.

Thanks @hartwork for the quick help!

**Comment by hartwork** [comment]
@FrederikLauber you're welcome, thanks for sharing/documenting the summary on the underlying problem for other users :+1:

**Comment by joshbode** [comment]
I was getting the same error, but for a different reason - if the `branch` output is set to use columns, then it seems like the output isn't being parsed correctly - I had to remove this option from my git config: 
```
[column]
  branch = column
```

**Comment by hartwork** [comment]
@joshbode very interesting, thanks for the report! (Please create a dedicated bug report next time: comments in closed issues are too easy to overlook and forget about.) I have created pull request #223 now with a candidate fix and a related test (that fails without the patch and succeeds with the patch, as you would expect). Is there a chance you could review and/or test drive the new code from the pull request?

**Comment by joshbode** [comment]
Thanks @hartwork ! Sorry, I should have done what you suggested :)

**Comment by joshbode** [comment]
@hartwork I'll take a look at the PR and try it out today

**Comment by hartwork** [comment]
@joshbode thank you! 👍

**Comment by hartwork** [comment]
@joshbode update: release 7.5.0 with the fix has hit GitHub and PyPI just now.
