### ISSUE TITLE
Name collides with git-extras' script with the same name

### ISSUE THREAD

**Issue by SuperSandro2000** [hartwork/git-delete-merged-branches#17]
Git Extras has a script which has the same name (https://github.com/tj/git-extras/blob/master/bin/git-delete-merged-branches) but only deleted branches locally. I have both installed and luckily is the the python script before the git-extras in my path. Do you have any idea how to solve this?

**Comment by hartwork** [comment]
Hi Sandro, nice to meet you!

Have you tried `python -m git_delete_merged_branches`?

**Comment by hartwork** [comment]
PS: If that^^ doesn't help, adding a second "entrypoint script" named `git-dmb` would also be an option.

**Comment by SuperSandro2000** [comment]
It works for me because I have it installed with ``pip --user`` and ``~/.local/bin/`` is preffered in my path but this prevents the module from being packaged in most distros. rg is ripgrep and fd fdfind in most distros. 

A good start would be to add this to the readme so that no one gets confused by this.

**Comment by hartwork** [comment]
I'm happy to extend the readme but I'm not sure yet what about, in particular. Are you suggesting to mention `python -m git_delete_merged_branches` in the readme as a mean to disambiguation or something else?

**Comment by hartwork** [comment]
Let me draft a change to the readme as a pull request — five minutes

**Comment by hartwork** [comment]
@SuperSandro2000 thanks a lot for bringing this up and for your review and ideas at #18. I think we're a lot better of with this now. I have just released 5.4.0 with the related changes.
