### ISSUE TITLE
Error: substring not found with no context

### ISSUE THREAD

**Issue by quodlibetor** [hartwork/git-delete-merged-branches#20]
I can't find the string "substring not found" in the repo so I'm not sure what might be causing this:

```console
$ git delete-merged-branches --verbose
# git config --list
Error: substring not found
```

**Comment by hartwork** [comment]
Hi @quodlibetor , thanks for taking this to a bug report!
Could you add `--debug` to the mix and share the backtrace that you're being presented? Thank you!

**Comment by hartwork** [comment]
PS: I'm assuming this is with the latest version 5.4.0?

**Comment by hartwork** [comment]
PS:
- Can you share your output of `git config --list`? If you censors parts of it, that should be fine.
- Is this one Windows? The current code assumes that `git config --list` output needs to be decoded as UTF-8 and I guess that's biting us here.
- The only other option I see is that there are any lines without an equal sign (`=`) in the output. If `git config --list | fgrep -v =` shows any output, then that's the case.

Would be cool if we can figure this out — thank you!

**Comment by quodlibetor** [comment]
Ah found it, I have this line in my config:

```text
```

```text
$ git config --list
alias.bt=!git lga --simplify-by-decoration | grep -v 'tag[^,]*)' | grep -Ev $( git branch --all --merged  | sed -E -e 's/ //g' -e '/^\*/d' | tr '
' '|' | sed -E 's/(\|$|^\|)//g' )
```

**Comment by quodlibetor** [comment]
Updated traceback for 6.0:

```
Traceback (most recent call last):
  File "/Users/bwm/.local/pipx/venvs/git-delete-merged-branches/lib/python3.8/site-packages/git_delete_merged_branches/_cli.py", line 115, in _inner_main
    _innermost_main(config, messenger)
  File "/Users/bwm/.local/pipx/venvs/git-delete-merged-branches/lib/python3.8/site-packages/git_delete_merged_branches/_cli.py", line 90, in _innermost_main
    git_config = dmb.ensure_configured(config.force_reconfiguration)
  File "/Users/bwm/.local/pipx/venvs/git-delete-merged-branches/lib/python3.8/site-packages/git_delete_merged_branches/_engine.py", line 134, in ensure_configured
    git_config = self._git.extract_git_config()
  File "/Users/bwm/.local/pipx/venvs/git-delete-merged-branches/lib/python3.8/site-packages/git_delete_merged_branches/_git.py", line 68, in extract_git_config
    equal_sign_index = line.index('=')
ValueError: substring not found
Error: substring not found
```

**Comment by hartwork** [comment]
> Ah found it, I have this line in my config:
> 
> ```
> bt = !"git lga --simplify-by-decoration | grep -v 'tag[^,]*)' | grep -Ev $( git branch --all --merged  | sed -E -e 's/ //g' -e '/^\\*/d' | tr '\n' '|' | sed -E 's/(\\|$|^\\|)//g' )"
> ```

When I stuff that line into my `.git/config`, it somehow ends up as two lines and causes trouble for me, e.g.:

```
# git config --list | fgrep -v =
' '|' | sed -E 's/(\|$|^\|)//g' )
```

**Comment by hartwork** [comment]
I found out that `git config --list` interprets `\n` that you have in there and turns it into an actual newline!
If we put `bt = !"echo 'A\nB\nC'"` in `.git/config`, `git bt` will show:
```console
# git bt
A
B
C
```
From `man git-config`:
> Inside double quotes, double quote " and backslash \ characters must be escaped: use \" for " and \\ for \.
>
> The following escape sequences (beside \" and \\) are recognized: \n for newline character (NL), \t for horizontal tabulation (HT, TAB) and \b for backspace (BS). Other char escape sequences (including octal escape sequences) are invalid.

So a line `one = !"echo \nalias.two=hello"` can fool the current parser to believe that a key `alias.two` is set to value `hello` while there is only alias `one` — interesting!

Let me think more how to best address this condition.

For a workaround, you could try replacing `'\n'` by `'\\n'` or `$'\\n'` or so — haven't tried myself yet.

**Comment by hartwork** [comment]
@quodlibetor I have just released version 6.0.1 with a fix. Please let me know how it works for you :pray:

**Comment by quodlibetor** [comment]
Yes it does indeed work for me, thanks!

**Comment by hartwork** [comment]
Glad to hear, thanks for the update! :+1:
