### ISSUE TITLE
Configuration text does not wrap in terminal and is cut off

### ISSUE THREAD

**Issue by pwaring** [hartwork/git-delete-merged-branches#21]
I've just installed and run the latest version of git-delete-merged-branches (5.4.0 according to `--version`) and when I run the command for the first time in a repository the text does not wrap at the right side of the terminal and is cut off instead.

Example:

```
== Configure git-delete-merged-branches for this repository ==
 [1/3] For a branch to be considered fully merged, which other branches must it

 (Press [Space] to toggle selection, [Enter]/[Return] to accept, [Ctrl]+[C] to
```

![image](https://user-images.githubusercontent.com/433556/90493842-c48ab980-e13a-11ea-9088-979a7ef9f536.png)

If I maximise the terminal I can see the full line. This problem doesn't occur with any other git-related commands, e.g. if I run `git log` lines are wrapped as I would expect, and if I increase the width of the window the lines are redrawn to fit.

The terminal I'm using is the default shipped with Xubuntu 20.04: xfce-terminal 0.8.9.1. The same issue occurs with xterm (353).

**Comment by hartwork** [comment]
Hi Paul, nice to meet you!

>  the text does not wrap at the right side of the terminal and is cut off instead.

True, that's how https://github.com/wong2/pick — that git-delete-merged-branches currently relies on — works (but I might switch). I agree it's no optimal. Once [Curses](https://en.wikipedia.org/wiki/Curses_(programming_library)) enters the game, wrapping is probably not something we get out of the box. I could try narrower text and more lines. Any other ideas?

**Comment by hartwork** [comment]
I'm experimenting with a substitute to `pick` that does come with wrapping; stay tuned :smiley:

**Comment by hartwork** [comment]
I have just released version 6.0.0 with wrapping. Please let me know how it works for you :pray:

**Comment by pwaring** [comment]
Thanks, that seems to work. It wraps the text, although the wrap can happen at any point during the text so you can end up with things like:

```
[1/3] For a branch to be considered fully merged, which other branches must it h
ave been merged to?
```

I don't know if the alternative to pick has an option to wrap on word boundaries - if it does that would be even better (but not essential).

**Comment by hartwork** [comment]
Thanks for the feedback. I'm using https://github.com/sebageek/clintermission now which uses https://github.com/prompt-toolkit/python-prompt-toolkit under the hood. I think personally, I'm good enough with the current wrapping for now. If you want to research word wrapping in prompt-toolkit more, that would be welcome. I'll close this as fixed for now.
