### ISSUE TITLE
Can't delete remote branches if there is a tag with the same name

### ISSUE THREAD

**Issue by jameshulse** [hartwork/git-delete-merged-branches#27]
I have run into an issue while deleting remote branches on a large repository. The error during the `git push --delete` command in the console is:
```
error: dst refspec <branch name> matches more than one
```
It turns out there is a branch and tag with the exact same name. I found likely reproduction steps and a resolution while googling: https://dzone.com/articles/git-having-branchtag-same-name

**Comment by hartwork** [comment]
Hi James, thanks for reporting this issue! I agree with you that it's a bug. I'm optimistic that I'll find time to work on a fix shortly.

**Comment by hartwork** [comment]
@jameshulse I have released version 6.0.5 with a fix now. Please re-open this ticket as needed.
