### ISSUE TITLE
Print deleted branch names with `--yes`

### ISSUE THREAD

**Issue by hauntsaninja** [hartwork/git-delete-merged-branches#37]
Thanks for the great tool!

Currently, running `git delete-merged-branches --yes` does not actually show you which branches are deleted. Without `--yes`, the confirmation prompt provides this information. The information can be found with `--verbose`, but that's not ergonomic.

**Comment by hartwork** [comment]
Hi @hauntsaninja , I'm glad you find git-delete-merged-branches useful. May I ask how you heard about it?

You have a point here about reporting deleting branches. I have a candidate implementation in pull request #38 now. This implementation always reports on deleted branches (even without `--yes`), matching `git branch -d` behavior. If it turns out too noisy, I would consider adding a `--quiet` flag on top, later. 
If you can help with code review and/or local testing, that would be welcome and appreciated. I'm looking forward to your feedback.

**Comment by hauntsaninja** [comment]
I'm not sure how I heard about it, tbh. I had my own bad version of this, which couldn't deal with squashed merges, so I think I just went looking for a better solution.

#38 works great for me, thank you so much!

Possible feedback (totally ignorable, don't feel strongly about):
- Like you say, maybe a little redundant when run without `--yes`, but whatever.
- You mentioned matching `git branch -d` behaviour. We don't quite do that since we don't report the hashes. We could just not capture subprocess output, like we currently do for `git pull`. (This would get rid of the exception handling + reporting stuff, which is the trickiest thing in the PR)

**Comment by hartwork** [comment]
> I'm not sure how I heard about it, tbh. I had my own bad version of this, which couldn't deal with squashed merges, so I think I just went looking for a better solution.

Thanks for sharing, cool that you find out.

> #38 works great for me, thank you so much!

Thanks for having a closer look.

> Possible feedback (totally ignorable, don't feel strongly about):
> 
> * Like you say, maybe a little redundant when run without `--yes`, but whatever.

I think it's more consistent and self-explaining this way. Let's see if we get reports about it being annoying or so in the next few weeks.

>  * You mentioned matching `git branch -d` behaviour. We don't quite do that since we don't report the hashes. We could just not capture subprocess output, like dmb currently does for `git pull`. (This would get rid of the exception handling + reporting stuff, which is the trickiest thing in the PR)

I've been thinking about that aspect a bit as well. Let me think about that more. For now I have merged status quo. PyPI now has version 6.1.0 with that feature.

**Comment by hauntsaninja** [comment]
Sounds great, thank you!

**Comment by hartwork** [comment]
@hauntsaninja I thought more about your feedback. The `git branch (-d|-D) <branch>` stdout already includes not only the branch names but the original hashes, so letting that through to the user would add value on the ex-hashes and look familiar.
It would also be in alignment with the stderr of `git push --delete <remote> <branch>` also mentioning deleted branches and going to the user as of today. (The choice of stdout versus stderr has been made by Git and is not too important in my view, I just wanted to be precise in my explanation.)

With that said, if you have time to review and/or test pull request #39 that would be welcome and appreciated. Thanks in advance! :pray:

**Comment by hauntsaninja** [comment]
Thanks, tried it out and it works great!

**Comment by hartwork** [comment]
Thanks, it is included with 6.2.0 on PyPI now.
