### ISSUE TITLE
I made a package for ArchLinux

### ISSUE THREAD

**Issue by rnestler** [hartwork/git-delete-merged-branches#49]
Hi @hartwork 
Just wanted to let you know that I packaged this application for ArchLinux on the AUR: https://aur.archlinux.org/packages/git-delete-merged-branches/

**Comment by hartwork** [comment]
@rnestler cool! One thing I noticed in the packaging is that limiting Python to version >=3.7 seems missing. Out of all the version operators, that one is essential, e.g. see 72e5042615739f85b40ca97fead4c030d267b69b. What do you think?

**Comment by rnestler** [comment]
@hartwork I actually don't know how to limit the Python version to >=3.7. I mean the only official supported Python version on ArchLinux is 3.10 anyways. 3.6 - 3.9 are only available from the AUR, so I guess it isn't much of a problem in practice. But I'll check if I find out how ArchLinux packages are supposed to specify interpreter version dependencies.

Also 3.6 is end of life in a few days (2021-12-23) it is expected that project don't support it anymore :slightly_smiling_face:

**Comment by hartwork** [comment]
@rnestler based on https://wiki.archlinux.org/title/PKGBUILD#depends I believe `depends=('python>=3.7' [..])` may be the right syntax. The `python (python35, python38, python36, python37, python310, python311, python39)` at the buttom of https://aur.archlinux.org/packages/git-delete-merged-branches/ just doesn't look right. That list seems to be from AUR packages that also "provide" package `python`. People running into crashes from accidental execution with the wrong version of Python is just a waste of everyone's time, I happen to have worked on something [just like that](https://github.com/git-big-picture/git-big-picture/issues/34) yesterday.

**Comment by rnestler** [comment]
OK fixed it. AUR still shows `python (python35, python38, python36, python37, python310, python311, python39)`, but I guess pacman would now complain if one tried to use it with only `python35` installed.

**Comment by hartwork** [comment]
@rnestler awesome, thanks for going the extra mile! :beers: 

I'm unsure if it's worth to extend the readme with a specific line for every distro that has packaging; it would be [Arch and nixOS today](https://repology.org/project/git-delete-merged-branches/versions) but likely more in the future. Do you see strong value in such text or should we close the ticket as information and done now?

**Comment by rnestler** [comment]
> Do you see strong value in such text

I think there is some value in it. I opened https://github.com/hartwork/git-delete-merged-branches/pull/50 with install instructions for Arch Linux.

**Comment by hartwork** [comment]
@rnestler thanks again for getting in touch, improving dependencies and the pull request :+1: I'll close the ticket now.
