### ISSUE TITLE
Error while executing: One or more existing target branch is required.

### ISSUE THREAD

**Issue by dennisc9** [hartwork/git-delete-merged-branches#72]
I keep getting this error while executing this command `git-delete-merged-branches --effort=3`

`Error: One or more existing target branch is required.`

is there a way to reset this so I can get the prompts back?

**Comment by hartwork** [comment]
Hi @dennisc9 is there a chance to learn more about your environment and why you may be running into this situation?
The second part sounds like you may be looking for the `--configure` argument?

**Comment by hartwork** [comment]
No reply for 3 weeks, closing.
