### ISSUE TITLE
Global branch keep list

### ISSUE THREAD

**Issue by SuperSandro2000** [hartwork/git-delete-merged-branches#73]
I have the same repository cloned on 3+ machines and work on all of them. Sometimes I delete branches which are technically merged but I would like to keep. I don't know an easy way to sync the .git/config file to all those machines but would it be possible to have a global config with branch names that should always be kept?

**Comment by hartwork** [comment]
Hi @SuperSandro2000 ,

to mark a branch as to keep (i.e. to be excluded) internally git-delete-merged-branches does this:
```console
$ git config branch.<branch_name_here>.dmb-excluded true
```

So if you do the same with `--global` that should work across repositories. What do you think?

Best, Sebastian

**Comment by hartwork** [comment]
Closing as "answered + no replies for two weeks" as part of housekeeping. Happy to re-open as needed.

**Comment by SuperSandro2000** [comment]
Didn't have to much time to try that out. Lets juts hope that the following for all long living nixpkgs branches worked.

``git config --global "branch.staging-next.dmb-excluded" true``
