### ISSUE TITLE
Can't select branch as merge target

### ISSUE THREAD

**Issue by tommy-couzens** [hartwork/git-delete-merged-branches#81]
Hi

Love the idea of this package and have been looking for something like this for a long time!

Unfortunately when I run it, it gives me a selection of which branch as a merge target, and I can scroll down the list using arrows keys, but I can't work out how to select one.

<img width="374" alt="image" src="https://user-images.githubusercontent.com/30808129/183062245-b74c8357-9502-43fb-a2d8-826daab2945e.png">

I've tried pressing enter, right arrow key, tab to no avail! Any help here?

I've also tried using passing the branch flag, running `git-delete-merged-branches --branch main` but I can the same selection screen

I'm using MacOS

**Comment by hartwork** [comment]
Hi @tommy-couzens ,

it looks like this over here on GNU/Linux in Yakuake:

![git-dmb-Screenshot_20220805_232242](https://user-images.githubusercontent.com/1577132/183207492-6f2297ab-00a0-4f5c-8b24-cc859bc1aae8.png)

To go forward, please help me understand:
- Does it not show a legend like that^^ for you?
- Does space bar work to toggle selection?
- Which version of the software are you using? Is this 7.0.0 off homebrew?

Thanks and best, Sebastian

PS: Here's how I produced that shot on a Bash Linux shell:
```console
# cd "$(mktemp -d)"
# git init &>/dev/null
# git config user.name support-issue-81
# git config user.email foo@bar.invalid
# git commit --allow-empty -m Dummy
# virtualenv --python=python3.10 venv
# source venv/bin/activate
# pip install git-delete-merged-branches
# git branch -m main
# for i in dockerfile-yarn-order filter-test-containers-with-parallel fix-deployment-overwriting-hpa fix-less-than-63-bug kaniko-provision local-testing-old no-jira/refactor production-azure-devops ; do git branch "${i}"; done
# git-delete-merged-branches --configure
```

**Comment by tommy-couzens** [comment]
Hello! Thanks for the thorough response

> Does it not show a legend like that^^ for you?

It could not see it before, and now I've discovered it was because I have so many branches it was not shown on screen.

<img width="955" alt="image" src="https://user-images.githubusercontent.com/30808129/183441363-eda589d4-f164-4b20-9645-667d37cc2a34.png">


Expanding my terminal size I can now see it:

<img width="930" alt="image" src="https://user-images.githubusercontent.com/30808129/183441412-0f8a5c64-af4b-469a-80e9-f26727512d6f.png">



> Does space bar work to toggle selection?

Yes, thanks spacebar works.

> Which version of the software are you using? Is this 7.0.0 off homebrew?
Yes it is 7.0.0 from homebrew

So now I can select my merge branch in stage 1, but I can't see the instructions on how to do stage 2 even with a very large terminal, because I have so many branches

<img width="659" alt="image" src="https://user-images.githubusercontent.com/30808129/183441899-272e890f-78e7-4bc9-9354-88dd8dd92f2f.png">


I appreciate I may have a silly number of branches, but this is precisely why I downloaded your package to help sort this out!

**Comment by hartwork** [comment]
@tommy-couzens thanks for the update. Glad to hear that spacebar works for you, in general. Regarding the cut-off, I understand the issue now. Let me play with an idea for a fix.

**Comment by hartwork** [comment]
@tommy-couzens could you try out pull request #83? To get it running in no time:

```bash
cd "$(mktemp -d)"
git clone --depth 1 --branch issue-81-live-config-preserve-header-and-footer https://github.com/hartwork/git-delete-merged-branches
cd git-delete-merged-branches/
python3 -m venv venv/
source venv/bin/activate
pip install -e .
for i in {1..70}; do git branch "${i}"; done
git-delete-merged-branches --configure
```

**Comment by tommy-couzens** [comment]
Hey, thanks for the quick response.

I tried your instructions as above but get the same issue of not being able to see the instructions

I can't see the even if I scroll to the bottom


![image](https://user-images.githubusercontent.com/30808129/183711749-48acae00-4c7a-4706-8d26-6f04cc54cf31.png)

**Comment by hartwork** [comment]
@tommy-couzens it looks like you're runnng the wrong code on the right repository. I'm not sure yet why that would happen, but this rendering seems unlikely to originate from the new code. My current best guess is that (1) you have installed git-delete-merged-branches somewhere and (2) the shells session has the previous command location hash. Commands that could be of help would be `hash -t git-delete-merged-branches` and `hash [-d] git-delete-merged-branches`. I have also bumped the version to 7.1.0 now on that branch so that `git-delete-merged-branches --version` can be used to tell old and new code apart. Please report back if that helped figuring out the unexpected results.

In the meantime, I'll try to add some visual indicator that the list is not presented in full, if reasonably easy possible.

**Comment by hartwork** [comment]
@tommy-couzens any chance you could give this another shot?
